### PR TITLE
Make cross platform

### PR DESCRIPTION
**Pull request by friism**

### CODE REVIEW

**Comment by friism** [comment]
@ctolkien let me know if there are any changes you want for this PR or feel free to close it if it's not appropriate for your sample.

**Comment by ctolkien** [comment]
@friism  - I just need a bit of time to update the posts to mention what's going on, as things like kestrel haven't been explained. Hopefully in the next day or so.

**Comment by ctolkien** [comment]
Project is RIP!

**Comment by friism** [comment]
❤️

**Pull request closed without merging**
